[platformio]
src_dir = examples
default_envs = teensy40-benchmark

[env:teensy40-benchmark]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<main.cpp>
    -<j6510_benchmark/>
    -<j6510_basic_demo/>
build_unflags =
    -std=gnu++11
    -std=gnu++14
build_flags =
    -std=gnu++17
    -DJ6510_ENABLE_BLOCK_CACHE=1

[env:rp2040-pico-benchmark]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<main.cpp>
    -<j6510_benchmark/>
    -<j6510_basic_demo/>
build_flags =
    -DJ6510_ENABLE_BLOCK_CACHE=1

[env:esp32s2-saola-benchmark]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-210
monitor_port = /dev/cu.usbserial-210
build_src_filter =
    +<main.cpp>
    -<j6510_benchmark/>
    -<j6510_basic_demo/>
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DJ6510_ENABLE_BLOCK_CACHE=1
    -DBOARD_HAS_PSRAM

[env:esp32s2-saola-fast]
extends = env:esp32s2-saola-benchmark
build_unflags =
    ${env:esp32s2-saola-benchmark.build_unflags}
    -Os
build_flags =
    ${env:esp32s2-saola-benchmark.build_flags}
    -O3
    -DJ6510_FAST_CODE_ATTR=IRAM_ATTR

[env:esp32s2-saola-basic-demo]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-210
monitor_port = /dev/cu.usbserial-210
build_src_filter =
    +<main.cpp>
    -<j6510_benchmark/>
    -<j6510_basic_demo/>
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.5
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DJ6510_ENABLE_BLOCK_CACHE=0
    -DJ6510_BUILD_BASIC_DEMO
    -DBOARD_HAS_PSRAM
